name: Release Notes
on: [push]
jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Draft Release
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
